"""
regions.py — UN M49 sub-region assignments for all BACI country names.

REGION_MAP maps each BACI country name to one of:
  Western Africa, Eastern Africa, Northern Africa, Middle Africa, Southern Africa,
  Western Europe, Eastern Europe, Northern Europe, Southern Europe,
  Northern America, Central America, Caribbean, South America,
  Western Asia, Central Asia, Southern Asia, South-eastern Asia, Eastern Asia,
  Oceania, Other

Covers all countries in COUNTRY_CONTINENT_MAP plus common extras from BACI data.
Source: UN M49 standard (https://unstats.un.org/unsd/methodology/m49/).
"""

REGIONS_ORDERED: list[str] = [
    "Western Africa",
    "Eastern Africa",
    "Northern Africa",
    "Middle Africa",
    "Southern Africa",
    "Western Europe",
    "Northern Europe",
    "Southern Europe",
    "Eastern Europe",
    "Northern America",
    "Central America",
    "Caribbean",
    "South America",
    "Western Asia",
    "Central Asia",
    "Southern Asia",
    "South-eastern Asia",
    "Eastern Asia",
    "Oceania",
    "Other",
]

REGION_MAP: dict[str, str] = {
    # ── Western Africa ──────────────────────────────────────────────────────────
    "Benin":             "Western Africa",
    "Burkina Faso":      "Western Africa",
    "Cabo Verde":        "Western Africa",
    "Côte d'Ivoire":     "Western Africa",
    "Gambia":            "Western Africa",
    "Ghana":             "Western Africa",
    "Guinea":            "Western Africa",
    "Guinea-Bissau":     "Western Africa",
    "Liberia":           "Western Africa",
    "Mali":              "Western Africa",
    "Mauritania":        "Western Africa",
    "Niger":             "Western Africa",
    "Nigeria":           "Western Africa",
    "Saint Helena":      "Western Africa",
    "Senegal":           "Western Africa",
    "Sierra Leone":      "Western Africa",
    "Togo":              "Western Africa",
    # ── Eastern Africa ──────────────────────────────────────────────────────────
    "Burundi":                   "Eastern Africa",
    "Comoros":                   "Eastern Africa",
    "Djibouti":                  "Eastern Africa",
    "Eritrea":                   "Eastern Africa",
    "Ethiopia":                  "Eastern Africa",
    "Kenya":                     "Eastern Africa",
    "Madagascar":                "Eastern Africa",
    "Malawi":                    "Eastern Africa",
    "Mauritius":                 "Eastern Africa",
    "Mayotte (Overseas France)": "Eastern Africa",
    "Mozambique":                "Eastern Africa",
    "Rwanda":                    "Eastern Africa",
    "Seychelles":                "Eastern Africa",
    "Somalia":                   "Eastern Africa",
    "South Sudan":               "Eastern Africa",
    "Uganda":                    "Eastern Africa",
    "United Rep. of Tanzania":   "Eastern Africa",
    "Zambia":                    "Eastern Africa",
    "Zimbabwe":                  "Eastern Africa",
    # ── Northern Africa ─────────────────────────────────────────────────────────
    "Algeria": "Northern Africa",
    "Egypt":   "Northern Africa",
    "Libya":   "Northern Africa",
    "Morocco": "Northern Africa",
    "Sudan":   "Northern Africa",
    "Tunisia": "Northern Africa",
    # ── Middle Africa ───────────────────────────────────────────────────────────
    "Angola":                 "Middle Africa",
    "Cameroon":               "Middle Africa",
    "Central African Rep.":   "Middle Africa",
    "Chad":                   "Middle Africa",
    "Congo":                  "Middle Africa",
    "Dem. Rep. of the Congo": "Middle Africa",
    "Equatorial Guinea":      "Middle Africa",
    "Gabon":                  "Middle Africa",
    "Sao Tome and Principe":  "Middle Africa",
    # ── Southern Africa ─────────────────────────────────────────────────────────
    "Botswana":    "Southern Africa",
    "Eswatini":    "Southern Africa",
    "Lesotho":     "Southern Africa",
    "Namibia":     "Southern Africa",
    "South Africa": "Southern Africa",
    # ── Western Europe ──────────────────────────────────────────────────────────
    "Austria":     "Western Europe",
    "Belgium":     "Western Europe",
    "France":      "Western Europe",
    "Germany":     "Western Europe",
    "Luxembourg":  "Western Europe",
    "Netherlands": "Western Europe",
    "Switzerland": "Western Europe",
    # ── Northern Europe ─────────────────────────────────────────────────────────
    "Denmark":        "Northern Europe",
    "Estonia":        "Northern Europe",
    "Finland":        "Northern Europe",
    "Iceland":        "Northern Europe",
    "Ireland":        "Northern Europe",
    "Latvia":         "Northern Europe",
    "Lithuania":      "Northern Europe",
    "Norway":         "Northern Europe",
    "Sweden":         "Northern Europe",
    "United Kingdom": "Northern Europe",
    # ── Southern Europe ─────────────────────────────────────────────────────────
    "Albania":          "Southern Europe",
    "Andorra":          "Southern Europe",
    "Bosnia Herzegovina": "Southern Europe",
    "Croatia":          "Southern Europe",
    "Gibraltar":        "Southern Europe",
    "Greece":           "Southern Europe",
    "Italy":            "Southern Europe",
    "Malta":            "Southern Europe",
    "Montenegro":       "Southern Europe",
    "North Macedonia":  "Southern Europe",
    "Portugal":         "Southern Europe",
    "San Marino":       "Southern Europe",
    "Serbia":           "Southern Europe",
    "Slovenia":         "Southern Europe",
    "Spain":            "Southern Europe",
    # ── Eastern Europe ──────────────────────────────────────────────────────────
    "Belarus":            "Eastern Europe",
    "Bulgaria":           "Eastern Europe",
    "Czechia":            "Eastern Europe",
    "Hungary":            "Eastern Europe",
    "Poland":             "Eastern Europe",
    "Rep. of Moldova":    "Eastern Europe",
    "Romania":            "Eastern Europe",
    "Russian Federation": "Eastern Europe",
    "Slovakia":           "Eastern Europe",
    "Ukraine":            "Eastern Europe",
    # ── Northern America ────────────────────────────────────────────────────────
    "Bermuda":                   "Northern America",
    "Canada":                    "Northern America",
    "Greenland":                 "Northern America",
    "Saint Pierre and Miquelon": "Northern America",
    "USA":                       "Northern America",
    # ── Central America ─────────────────────────────────────────────────────────
    "Belize":      "Central America",
    "Costa Rica":  "Central America",
    "El Salvador": "Central America",
    "Guatemala":   "Central America",
    "Honduras":    "Central America",
    "Mexico":      "Central America",
    "Nicaragua":   "Central America",
    "Panama":      "Central America",
    # ── Caribbean ───────────────────────────────────────────────────────────────
    "Anguilla":                         "Caribbean",
    "Antigua and Barbuda":              "Caribbean",
    "Aruba":                            "Caribbean",
    "Bahamas":                          "Caribbean",
    "Barbados":                         "Caribbean",
    "Bonaire":                          "Caribbean",
    "Br. Virgin Isds":                  "Caribbean",
    "Cayman Isds":                      "Caribbean",
    "Cuba":                             "Caribbean",
    "Curaçao":                          "Caribbean",
    "Dominica":                         "Caribbean",
    "Dominican Rep.":                   "Caribbean",
    "Grenada":                          "Caribbean",
    "Haiti":                            "Caribbean",
    "Jamaica":                          "Caribbean",
    "Montserrat":                       "Caribbean",
    "Saint Barthélemy":                 "Caribbean",
    "Saint Kitts and Nevis":            "Caribbean",
    "Saint Lucia":                      "Caribbean",
    "Saint Maarten":                    "Caribbean",
    "Saint Vincent and the Grenadines": "Caribbean",
    "Trinidad and Tobago":              "Caribbean",
    "Turks and Caicos Isds":            "Caribbean",
    # ── South America ───────────────────────────────────────────────────────────
    "Argentina":                        "South America",
    "Bolivia (Plurinational State of)": "South America",
    "Brazil":                           "South America",
    "Chile":                            "South America",
    "Colombia":                         "South America",
    "Ecuador":                          "South America",
    "Falkland Isds (Malvinas)":         "South America",
    "Guyana":                           "South America",
    "Paraguay":                         "South America",
    "Peru":                             "South America",
    "Suriname":                         "South America",
    "Uruguay":                          "South America",
    "Venezuela":                        "South America",
    # ── Western Asia ────────────────────────────────────────────────────────────
    "Armenia":              "Western Asia",  # UN M49 (appears in _EUROPE in data_loader)
    "Azerbaijan":           "Western Asia",
    "Bahrain":              "Western Asia",
    "Cyprus":               "Western Asia",  # UN M49 (appears in _EUROPE in data_loader)
    "Georgia":              "Western Asia",  # UN M49 (appears in _EUROPE in data_loader)
    "Iran":                 "Western Asia",
    "Iraq":                 "Western Asia",
    "Israel":               "Western Asia",
    "Jordan":               "Western Asia",
    "Kuwait":               "Western Asia",
    "Lebanon":              "Western Asia",
    "Oman":                 "Western Asia",
    "Qatar":                "Western Asia",
    "Saudi Arabia":         "Western Asia",
    "State of Palestine":   "Western Asia",
    "Syria":                "Western Asia",
    "Türkiye":              "Western Asia",
    "United Arab Emirates": "Western Asia",
    "Yemen":                "Western Asia",
    # ── Central Asia ────────────────────────────────────────────────────────────
    "Kazakhstan":   "Central Asia",
    "Kyrgyzstan":   "Central Asia",
    "Tajikistan":   "Central Asia",
    "Turkmenistan": "Central Asia",
    "Uzbekistan":   "Central Asia",
    # ── Southern Asia ───────────────────────────────────────────────────────────
    "Afghanistan": "Southern Asia",
    "Bangladesh":  "Southern Asia",
    "Bhutan":      "Southern Asia",
    "India":       "Southern Asia",
    "Maldives":    "Southern Asia",
    "Nepal":       "Southern Asia",
    "Pakistan":    "Southern Asia",
    "Sri Lanka":   "Southern Asia",
    # ── South-eastern Asia ──────────────────────────────────────────────────────
    "Brunei Darussalam":      "South-eastern Asia",
    "Cambodia":               "South-eastern Asia",
    "Indonesia":              "South-eastern Asia",
    "Lao People's Dem. Rep.": "South-eastern Asia",
    "Malaysia":               "South-eastern Asia",
    "Myanmar":                "South-eastern Asia",
    "Philippines":            "South-eastern Asia",
    "Singapore":              "South-eastern Asia",
    "Thailand":               "South-eastern Asia",
    "Timor-Leste":            "South-eastern Asia",
    "Viet Nam":               "South-eastern Asia",
    # ── Eastern Asia ────────────────────────────────────────────────────────────
    "China":                       "Eastern Asia",
    "Dem. People's Rep. of Korea": "Eastern Asia",
    "Japan":                       "Eastern Asia",
    "Mongolia":                    "Eastern Asia",
    "Rep. of Korea":               "Eastern Asia",
    # ── Oceania ─────────────────────────────────────────────────────────────────
    "American Samoa":         "Oceania",
    "Australia":              "Oceania",
    "Christmas Isds":         "Oceania",
    "Cocos Isds":             "Oceania",
    "Cook Isds":              "Oceania",
    "Fiji":                   "Oceania",
    "FS Micronesia":          "Oceania",
    "French Polynesia":       "Oceania",
    "Guam":                   "Oceania",
    "Kiribati":               "Oceania",
    "Marshall Isds":          "Oceania",
    "Nauru":                  "Oceania",
    "New Caledonia":          "Oceania",
    "New Zealand":            "Oceania",
    "Niue":                   "Oceania",
    "Norfolk Isds":           "Oceania",
    "Palau":                  "Oceania",
    "Papua New Guinea":       "Oceania",
    "Pitcairn":               "Oceania",
    "Samoa":                  "Oceania",
    "Solomon Isds":           "Oceania",
    "Tokelau":                "Oceania",
    "Tonga":                  "Oceania",
    "Tuvalu":                 "Oceania",
    "Vanuatu":                "Oceania",
    "Wallis and Futuna Isds": "Oceania",
    # ── Other ───────────────────────────────────────────────────────────────────
    "Br. Indian Ocean Terr.": "Other",
    "Other Asia":             "Other",
}

# ── UN Major Regions (derived from sub-regions above) ─────────────────────────

_SUBREGION_TO_MAJOR: dict[str, str] = {
    "Western Africa":    "Africa",
    "Eastern Africa":    "Africa",
    "Northern Africa":   "Africa",
    "Middle Africa":     "Africa",
    "Southern Africa":   "Africa",
    "Western Europe":    "Europe",
    "Northern Europe":   "Europe",
    "Southern Europe":   "Europe",
    "Eastern Europe":    "Europe",
    "Northern America":  "Americas",
    "Central America":   "Americas",
    "Caribbean":         "Americas",
    "South America":     "Americas",
    "Western Asia":      "Asia",
    "Central Asia":      "Asia",
    "Southern Asia":     "Asia",
    "South-eastern Asia": "Asia",
    "Eastern Asia":      "Asia",
    "Oceania":           "Oceania",
    "Other":             "Other",
}

MAJOR_REGIONS_ORDERED: list[str] = [
    "Africa",
    "Americas",
    "Asia",
    "Europe",
    "Oceania",
]

MAJOR_REGION_MAP: dict[str, str] = {
    country: _SUBREGION_TO_MAJOR[subregion]
    for country, subregion in REGION_MAP.items()
}
